package a2a

const (
	ErrorUnsupportedOperation ErrorCode = "unsupported_operation"
	ErrorInvalidSubject       ErrorCode = "invalid_subject"
	ErrorInvalidEnvelope      ErrorCode = "invalid_envelope"
	ErrorPolicyDenied         ErrorCode = "policy_denied"
	ErrorCapabilityDenied     ErrorCode = "capability_denied"
	ErrorTimeout              ErrorCode = "timeout"
	ErrorInternal             ErrorCode = "internal"
	ErrorUnsupportedVersion   ErrorCode = "unsupported_version"
	ErrorUnsupportedBinding   ErrorCode = "unsupported_binding"
	ErrorUnauthorizedSender   ErrorCode = "unauthorized_sender"
	ErrorUnauthorizedTarget   ErrorCode = "unauthorized_target"
	ErrorUnknownAgent         ErrorCode = "unknown_agent"
	ErrorUnknownSkill         ErrorCode = "unknown_skill"
	ErrorChannelNotEnabled    ErrorCode = "channel_not_enabled"
	ErrorSenderNotAllowed     ErrorCode = "sender_not_allowed"
	ErrorSkillNotAllowed      ErrorCode = "skill_not_allowed"
	ErrorOverloaded           ErrorCode = "overloaded"
	ErrorTaskNotFound         ErrorCode = "task_not_found"
	ErrorTaskTerminal         ErrorCode = "task_terminal"
	ErrorCancelNotAllowed     ErrorCode = "cancel_not_allowed"
	ErrorInputNotExpected     ErrorCode = "input_not_expected"
	ErrorAuthNotSatisfied     ErrorCode = "auth_not_satisfied"
	ErrorStoreError           ErrorCode = "store_error"
)
